# Generated by Django 4.2.1 on 2023-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('newsId', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('theatreArt', 'Театр'), ('musicArt', 'Музыка'), ('danceArt', 'Танцы'), ('visualArt', 'Изобразительное искусство')], max_length=35)),
                ('publicationTime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
