# Generated by Django 4.2.1 on 2023-05-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table=None,
        ),
    ]
